In [187]:
import cv2 as cv
import numpy as np

In [188]:
#read image
img = cv.imread('image1.png')

In [189]:
#make it grayscale
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
print(gray)

[[163 163 163 ... 172 154 127]
 [163 156 163 ... 168 154 129]
 [163 163 163 ... 168 156 122]
 ...
 [ 40  43  48 ... 107 103  98]
 [ 43  43  50 ... 107 107 107]
 [ 40  43  54 ... 100 104 110]]


In [190]:
img.shape

(512, 512, 3)

In [191]:
gray.shape

(512, 512)

In [192]:
rgb_img = cv.imread('rgb_image.jpg')

In [193]:
rgb_img = cv.cvtColor(rgb_img, cv.COLOR_BGR2RGB)

In [194]:
rgb_img.shape

(360, 639, 3)

In [195]:
rgb_img_1 = cv.imread('colors.jpg')

In [196]:
rgb_img_1 = cv.cvtColor(rgb_img_1, cv.COLOR_BGR2RGB)

In [197]:
(R,G,B) = cv.split(img)

In [198]:
cv.namedWindow("Blue", cv.WINDOW_NORMAL)
cv.namedWindow("Green", cv.WINDOW_NORMAL)
cv.namedWindow("Red", cv.WINDOW_NORMAL)

In [199]:
cv.imshow("Blue", B)
cv.imshow("Green", G)
cv.imshow("Red", R)

In [200]:
cv.imwrite('Chanel_Red.jpg', R)
cv.imwrite('Chanel_Green.jpg', G)
cv.imwrite('Chanel_Blue.jpg',B)
if cv.waitKey(0):
    cv.destroyAllWindows()

In [201]:
(b,g,r)=img[0,0]
print(f"At Pixel (0,0) blue: {b}, green: {g}, red: {r}")

At Pixel (0,0) blue: 118, green: 138, red: 229


### Drawing

In [202]:
canvas = np.zeros((300, 300, 3), dtype="uint8")

In [203]:
green = (0, 255, 0)
cv.line(canvas, (0,0), (300,300), green, 1)
cv.imshow("canvas", canvas)
if cv.waitKey(0):
    cv.destroyAllWindows()

In [204]:
red = (0, 0, 255)
cv.line(canvas, (0,300), (300,0), red, 1)
cv.imshow("canvas", canvas)
if cv.waitKey(0):
    cv.destroyAllWindows()

In [205]:
blue = (255, 0 ,0)
cv.rectangle(canvas, (120,195), (180,105), blue, 5)
cv.imshow("canvas", canvas)
if cv.waitKey(0):
    cv.destroyAllWindows()

In [206]:
blue = (85, 0 ,0)
cv.rectangle(canvas, (120,195), (180, 105),blue, -1)
cv.imshow("canvas", canvas)
if cv.waitKey(0):
    cv.destroyAllWindows()

In [207]:
canvas = np.zeros((300, 300, 3), dtype="uint8")
(centerX, centerY) = (canvas.shape[1]//2, canvas.shape[0]//2)
white = (255, 255, 255)
for r in range(0, 150, 25):
    cv.circle(canvas, (centerX, centerY), r, white, 1)
cv.imshow("canvad", canvas)
if cv.waitKey(0):
    cv.destroyAllWindows()