# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [41]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [42]:
# Create a 1-dimensional NumPy array using np.array()
array_1d = np.array([1,2,3,4])
print(array_1d)
# Create a 2-dimensional NumPy array using np.array()
array_2d = np.array([[3,4,2], [1,3,2],])
print(array_2d)
# Create a 3-dimensional Numpy array using np.array()
array_3d = np.array([[[3,6,7], [1,5,9], [1,3,5]], [[4,6,8], [2,4,6], [1,3,5]]])
print(array_3d)

[1 2 3 4]
[[3 4 2]
 [1 3 2]]
[[[3 6 7]
  [1 5 9]
  [1 3 5]]

 [[4 6 8]
  [2 4 6]
  [1 3 5]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [43]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array_1d.shape, array_1d.ndim, array_1d.dtype, array_1d.size, type(array_1d)

((4,), 1, dtype('int64'), 4, numpy.ndarray)

In [44]:
# Attributes of 2-dimensional array
array_2d.shape, array_2d.ndim, array_2d.dtype, array_2d.size, type(array_2d)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [45]:
# Attributes of 3-dimensional array
array_3d.shape, array_3d.ndim, array_3d.dtype, array_3d.size, type(array_3d)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [46]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(array_2d)
print(df)

   0  1  2
0  3  4  2
1  1  3  2


In [47]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [48]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2 ,3))
print(zeros)


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [49]:
# Create an array within a range of 0 and 100 with step 3
array_4 = np.arange(0, 100, 3)
print(array_3d)

[[[3 6 7]
  [1 5 9]
  [1 3 5]]

 [[4 6 8]
  [2 4 6]
  [1 3 5]]]


In [50]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array_5 = np.random.randint(10, size=(7,2))
print(array_5)

[[9 1]
 [9 3]
 [7 6]
 [8 7]
 [4 1]
 [4 7]
 [9 8]]


In [51]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array_6 =np.random.random((3,5))    
print(array_6)

[[0.28093451 0.54269608 0.14092422 0.80219698 0.07455064]
 [0.98688694 0.77224477 0.19871568 0.00552212 0.81546143]
 [0.70685734 0.72900717 0.77127035 0.07404465 0.35846573]]


In [52]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
array_7 = np.random.randint(0, 10, size=(4,6))
print(array_7)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [53]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array_8 = np.random.randint(1, 10, size=(3,7))
print(array_8)
# Find the unique numbers in the array you just created
unique_numbers = np.unique(array_8)
print(unique_numbers)


[[9 1 3 7 4 9 3]
 [5 3 7 5 9 7 2]
 [4 9 2 9 5 2 4]]
[1 2 3 4 5 7 9]


In [54]:
# Find the 0'th index of the latest array you created
array_8[0][0]

np.int32(9)

In [55]:
# Get the first 2 rows of latest array you created
array_8[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]], dtype=int32)

In [56]:
# Get the first 2 values of the first 2 rows of the latest array
array_8[:2,:2]

array([[9, 1],
       [5, 3]], dtype=int32)

In [57]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array_9 = np.random.randint(0, 10, size=(3,5))
array_10 = np.ones((3,5)) 
print(array_9, array_10)

[[6 7 2 0 3]
 [1 7 3 1 5]
 [5 9 3 5 1]] [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [58]:
# Add the two arrays together
sum_array = array_9 + array_10
print(sum_array)

[[ 7.  8.  3.  1.  4.]
 [ 2.  8.  4.  2.  6.]
 [ 6. 10.  4.  6.  2.]]


In [59]:
# Create another array of ones of shape (5, 3)
array_11 = np.ones((5,3))
print(array_11)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [60]:
# Try add the array of ones and the other most recent array together
array_11 + sum_array  


ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [61]:
# Create another array of ones of shape (3, 5)
ones2 = np.ones((3,5))
print(ones2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [62]:
# Subtract the new array of ones from the other most recent array
array_9 - ones2

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [63]:
# Multiply the ones array with the latest array
ones2 * array_9

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [64]:
# Take the latest array to the power of 2 using '**'
array_9 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [65]:
# Do the same thing with np.square()
np.square(array_9)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [66]:
# Find the mean of the latest array using np.mean()
np.mean(array_9)

np.float64(3.8666666666666667)

In [67]:
# Find the maximum of the latest array using np.max()
np.max(array_9)

np.int32(9)

In [68]:
# Find the minimum of the latest array using np.min()
np.min(array_9)

np.int32(0)

In [69]:
# Find the standard deviation of the latest array
np.std(array_9)

np.float64(2.578543947441829)

In [70]:
# Find the variance of the latest array
np.var(array_9)

np.float64(6.648888888888889)

In [71]:
# Reshape the latest array to (3, 5, 1)
np.reshape(array_9, (3,5,1))

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]], dtype=int32)

In [72]:
# Transpose the latest array
print(np.transpose(array_9))
array_9

[[6 1 5]
 [7 7 9]
 [2 3 3]
 [0 1 5]
 [3 5 1]]


array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]], dtype=int32)

What does the transpose do?

In [73]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_12 = np.random.randint(10, size=(3,3))
array_13 = np.random.randint(10, size=(3,2))
print(array_12, "\n" ,array_13)

[[9 1 9]
 [3 7 6]
 [8 7 4]] 
 [[1 4]
 [7 9]
 [8 8]]


In [74]:
# Perform a dot product on the two newest arrays you created
np.dot(array_12, array_13)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]], dtype=int32)

In [75]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_12 = np.random.randint(10, size=(4,3))
array_13 = np.random.randint(10, size=(4,3))
print(array_12, "\n" ,array_13)

[[0 8 6]
 [8 7 0]
 [7 7 2]
 [0 7 2]] 
 [[2 0 4]
 [9 6 9]
 [8 6 8]
 [7 1 0]]


In [76]:
# Perform a dot product on the two newest arrays you created
np.array_12.dot(array_13)

AttributeError: module 'numpy' has no attribute 'array_12'

It doesn't work. How would you fix it?

In [77]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(array_12, np.transpose(array_13))

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [78]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_12 = np.random.randint(10, size=(3,3))
array_13 = np.random.randint(10, size=(3,3))
print(array_12, "\n" ,array_13)

[[6 6 7]
 [4 2 7]
 [5 2 0]] 
 [[2 4 2]
 [0 4 9]
 [6 6 8]]


In [79]:
# Compare the two arrays with '>'
array_12 > array_13

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [80]:
# Compare the two arrays with '>='
array_12 >= array_13

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [81]:
# Find which elements of the first array are greater than 7
array_12 > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [82]:
# Which parts of each array are equal? (try using '==')
array_12 == array_13

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [83]:
# Sort one of the arrays you just created in ascending order
np.sort(array_12)

array([[6, 6, 7],
       [2, 4, 7],
       [0, 2, 5]], dtype=int32)

In [84]:
# Create an array of normally distributed random numbers
array_14 = np.random.normal(0, 1, size=(3,3))
print(array_14)

[[-0.61487576  0.33289244 -1.38071702]
 [-0.28080629 -0.05981726  0.96117377]
 [ 1.79428084  0.58068954  0.29765045]]


In [85]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.